version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - campus-connect-network

networks:
  campus-connect-network:
    driver: bridge 