name: production
on:
  workflow_run:
    workflows: ["Continuous Deployment Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  production-approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Production Deployment Approval
      run: |
        echo "✅ Production deployment approved!"
        echo "Environment: ${{ github.event.workflow_run.environment }}"
        echo "Workflow: ${{ github.event.workflow_run.name }}"
        echo "Run ID: ${{ github.event.workflow_run.id }}" 